### ISSUE TITLE
Publish to maven repository

### ISSUE THREAD

**Issue by gavingolden** [javadelight/delight-metrics#2]
Is the artifact already available somewhere?

**Comment by mxro** [comment]
Thank you for your message!

This artifact is not yet in Maven central but I will upload it and its dependencies. This might take a few days. Once it's done, I will notify you!

**Comment by mxro** [comment]
The artifact is now in Maven central. Sorry for the delay - a lot of dependent projects needed to be released first.

Hope this helps and let me know if there is anything else I can help with.
